### ISSUE TITLE
Add more obvious means to save an image

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/TheAwesomeResizer#11]
Drag&drop to save is often convenient (but not always), but it's not obvious. Maybe change the string in the empty image window to:
```
Drag and drop an image
to load/save
```

Also, how about adding an image-button (floppy icon) after the filename text control. It'll open a regular save file dialog.
The label could be changed from "Filename:" to "Save as:"

**Comment by janus2** [comment]
I like the label. I would prefer to avoid adding other widgets to the interface.

**Comment by humdingerb** [comment]
As you wish.
