### ISSUE TITLE
The application need a new vector icon

### ISSUE THREAD

**Issue by janus2** [HaikuArchives/TheAwesomeResizer#3]

**Comment by Meanwhile** [comment]
There's one in this icon pack: http://www.xs4all.nl/~rrvvww/HBBIv5.6.1.zip (name: TAResizer)

**Comment by CodeforEvolution** [comment]
This can be closed now.

**Comment by humdingerb** [comment]
Indeed, committed with 9fc84791562f75e5d2bc3b2bece0057f0b86e685. Thanks!
